name: branch

on:
  push:
    tags-ignore:
      - '**'

jobs:
  branch:
    name: Test, Build Source, Build Image
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: go-redirector
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.1'
      - name: Setup Vars
        run: |
          echo "BUILD_VERSION=$(cat .version)" >> $GITHUB_ENV
          echo "BUILD_SHA=$(echo $GITHUB_SHA | cut -c1-8)" >> $GITHUB_ENV
          echo "BUILD_DATE=$(date '+%Y.%m.%d-%T')" >> $GITHUB_ENV
      - name: Calc coverage
        run: |
          go test -v -covermode=count -coverprofile=coverage.out
          - name: Convert coverage.out to coverage.lcov
            uses: jandelgado/gcov2lcov-action@v1.0.8
          - name: Coveralls
            uses: coverallsapp/github-action@v1.1.2
            with:
              github-token: ${{ secrets.github_token }}
              path-to-lcov: coverage.lcov
      - name: Compile
        run: |
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build \
              -ldflags="-s -w" \
              -ldflags "-X main.BUILD_SHA=$BUILD_SHA \
                        -X main.BUILD_VERSION=$BUILD_VERSION \
                        -X main.BUILD_DATE=$BUILD_DATE" \
              -o dist/linux/$IMAGE_NAME-linux-amd64 main.go
      - name: Show binary version info
        run: dist/linux/$IMAGE_NAME-linux-amd64 -version
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./ci/Dockerfile
          context: .
          push: false
          tags: user/app:latest
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        if: success()
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Calc coverage
        run: |
          go test -v -covermode=count -coverprofile=coverage.out
      - name: Convert coverage.out to coverage.lcov
        uses: jandelgado/gcov2lcov-action@v1.0.8
      - name: Coveralls
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: coverage.lcov